apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotify-backend-hpa
  namespace: notspotify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spotify-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotify-clone-hpa
  namespace: notspotify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spotify-clone
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotify-admin-hpa
  namespace: notspotify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spotify-admin
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
