apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: "$2a$10$7EqJtq98hPqEX7fNZaFWoOhi59QnxqcCWQRfYn3B82/vJ0G3k8wqe"
  admin.passwordMtime: "2026-08-08T00:00:00Z"
  server.secretkey: "c3BvdGlmeS1hcmdvY2Qtc2VjcmV0LWtleS1wcm9kdWN0aW9uMTIzNA=="
