apiVersion: v1
kind: Service
metadata:
  name: spotify-clone
  namespace: {{ .Values.global.namespace }}
  labels:
    app: spotify-clone
    {{- include "notspotify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clone.service.type }}
  ports:
    - port: {{ .Values.clone.service.port }}
      targetPort: {{ .Values.clone.service.port }}
      protocol: TCP
      name: http
  selector:
    app: spotify-clone
