apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notspotify-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vikramT75/notspotify.git
    targetRevision: master
    path: helm/notspotify
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: notspotify
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
