apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: notspotify-instrumentation
  namespace: notspotify
spec:
  exporter:
    endpoint: http://notspotify-collector.notspotify.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
